sudo: required

services:
  - docker

before_install:
  - docker build -t aniejek/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true aniejek/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t aniejek/multi-client ./client
  - docker build -t aniejek/multi-nginx ./nginx
  - docker build -t aniejek/multi-server ./server
  - docker build -t aniejek/multi-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker tag aniejek/multi-client aniejek/multi-client:$VERSION.$TRAVIS_BUILD_NUMBER
  - docker tag aniejek/multi-nginx aniejek/multi-nginx:$VERSION.$TRAVIS_BUILD_NUMBER
  - docker tag aniejek/multi-server aniejek/multi-server:$VERSION.$TRAVIS_BUILD_NUMBER
  - docker tag aniejek/multi-worker aniejek/multi-worker:$VERSION.$TRAVIS_BUILD_NUMBER
  - docker push aniejek/multi-client
  - docker push aniejek/multi-nginx
  - docker push aniejek/multi-server
  - docker push aniejek/multi-worker
